[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
script = "contracts/script"
test = "contracts/test"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
og_testnet = "https://evmrpc-testnet.0g.ai"
og_mainnet = "https://evmrpc-mainnet.0g.ai"
